### ISSUE TITLE
uniapp 在安卓机上播放失败

### ISSUE THREAD

**Issue by lujiajiaj** [bosscheng/jessibuca-umi-app-hBuilderX-demo#3]
使用uniapp开发时， 运行到浏览器可以播放， 但是使用真机运行时报错，
报错信息1： Error in mounted hook: "TypeError: Cannot read property 'Jessibuca' of undefined"
报错信息2：TypeError: Cannot read property 'on' of null
另外， uniapp中没有window对象， new window.Jessibuca() 能创建出Jessibuca对象吗

**Comment by bosscheng** [comment]
你这个是打包成什么程序？目前只支持H5模式下面的播放。不支持小程序或者app下面。
